Login page draft
wkg7vb/Everything-Pizza-Porkchop-Sushi pull request #14
Opened 2024-10-07 21:37 UTC by egurung11

this is the draft for the login/register page, no logic - will need help connecting it with stuff

2024-10-07 21:39 UTC, egurung11 commented
![image](https://github.com/user-attachments/assets/9511219f-1fe9-4f8f-9ee7-41f62fa84c99)

^ does not look good, but is a base to start with, will change

2024-10-07 21:49 UTC, max-dejesus requested changes
o7

2024-10-07 21:49 UTC, max-dejesus commented on BAR/Components/Pages/Login.razor
> +
adding your own style is cool! however id recommend looking at the bootstrap docs to see what they offer for auto layouts and stuff, honestly makes it pretty simple

https://getbootstrap.com/docs/4.1/getting-started/introduction/

2024-10-07 21:49 UTC, max-dejesus commented on BAR/Components/Pages/Login.razor
> +            <button type="submit" class="loginbtn">Login</button>
forgot password button/link should be added here somewhere

2024-10-07 21:56 UTC, max-dejesus commented on BAR/Components/Pages/Login.razor
> +
additionally you can make css files titled after your razor file and itll pull in the css automatically (i.e. Landing.razor can have Landing.razor.css as its stylesheet)

2024-10-07 23:33 UTC, max-dejesus approved these changes
ok

2024-10-08 18:06 UTC, haley-v approved these changes
cool beans 👍

2024-10-09 15:14 UTC, merged